id: P010771
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01522
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༢༤་
  author: ''
  volumes:
    445734f114e04c87929c8f3f346af9fd:
      image_group_id: I5823
      title: ''
      volume_number: 1
      total_pages: 373
