id: P010771
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:23:47.104953
source_metadata:
  id: bdr:W00KG01522
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༢༤་
  author: ''
  volumes:
    445734f114e04c87929c8f3f346af9fd:
      image_group_id: I5823
      title: ''
      volume_number: 1
      total_pages: 373
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
