id: IEA2A2812
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:52:32+00:00'
last_modified: '2022-06-08T17:24:37.589805+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01522
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༢༤་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    617E:
      image_group_id: I5823
      title: ''
      total_pages: 373
      order: 1
      base_file: 617E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
